export const data = [
  {
    id: 1,
    name: 'Bulbasaur',
    type: ['grass', 'poison'],
    weaknesses: ['fire', 'flying', 'ice', 'psychic'],
    resistances: ['fighting', 'water', 'electric', 'grass', 'fairy'],
    immunities: [],
  },
  {
    id: 2,
    name: 'Ivysaur',
    type: ['grass', 'poison'],
    weaknesses: ['fire', 'flying', 'ice', 'psychic'],
    resistances: ['fighting', 'water', 'electric', 'grass', 'fairy'],
    immunities: [],
  },
  {
    id: 3,
    name: 'Venusaur',
    type: ['grass', 'poison'],
    weaknesses: ['fire', 'flying', 'ice', 'psychic'],
    resistances: ['fighting', 'water', 'electric', 'grass', 'fairy'],
    immunities: [],
  },
  {
    id: 4,
    name: 'Charmander',
    type: ['fire'],
    weaknesses: ['rock', 'water', 'ground'],
    resistances: ['fire', 'ice', 'bug', 'steel', 'grass', 'fairy'],
    immunities: [],
  },
  {
    id: 5,
    name: 'Charmeleon',
    type: ['fire'],
    weaknesses: ['rock', 'water', 'ground'],
    resistances: ['fire', 'ice', 'bug', 'steel', 'grass', 'fairy'],
    immunities: [],
  },
  {
    id: 6,
    name: 'Charizard',
    type: ['fire', 'flying'],
    weaknesses: ['rock', 'water', 'electric'],
    resistances: ['fire', 'fighting', 'bug', 'steel', 'grass', 'fairy'],
    immunities: ['ground'],
  },
  {
    id: 7,
    name: 'Squirtle',
    type: ['water'],
    weaknesses: ['grass', 'electric'],
    resistances: ['steel', 'fire', 'water', 'ice'],
    immunities: [],
  },
  {
    id: 8,
    name: 'Wartortle',
    type: ['water'],
    weaknesses: ['grass', 'electric'],
    resistances: ['steel', 'fire', 'water', 'ice'],
    immunities: [],
  },
  {
    id: 9,
    name: 'Blastoise',
    type: ['water'],
    weaknesses: ['grass', 'electric'],
    resistances: ['steel', 'fire', 'water', 'ice'],
    immunities: [],
  },
  {
    id: 10,
    name: 'Caterpie',
    type: ['bug'],
    weaknesses: ['rock', 'fire', 'flying'],
    resistances: ['grass', 'ground', 'fighting'],
    immunities: [],
  },
];
